### ISSUE TITLE
Make debug symbol flag optional

### ISSUE THREAD

**Issue by Whissi** [edenhill/mklove#7]
Hi,

I would also like to submit a PR which would make the following block from `modules/configure.cc` optional:
```bash
    # Add debug symbol flag (-g)
    # OSX 10.9 requires -gstrict-dwarf for some reason.
    mkl_meta_set cc_g_dwarf name "debug symbols compiler flag (-g...)"
    if [[ $MKL_DISTRO == "osx" ]]; then
	if mkl_compile_check cc_g_dwarf "" cont CC "-gstrict-dwarf"; then
	    mkl_mkvar_append CPPFLAGS CPPFLAGS "-gstrict-dwarf"
	else
	    mkl_mkvar_append CPPFLAGS CPPFLAGS "-g"
	fi
    else
	mkl_mkvar_append CPPFLAGS CPPFLAGS "-g"
    fi
```
Reason for doing that:
  1. You don't want `-g` in general. If your project is small, you don't mind but building a large project with `-g` if you aren't interested in debug information makes the compiled project unnecessary large.

  2. `-g` can cause troubles, see https://blog.flameeyes.eu/2011/08/are-g-options-really-safe

  3. Especially on Gentoo we don't like this option. People interested in debug information have their own options to build with debug information. So every package on Gentoo using *mklove* would need a patch to remove the code block. This is nothing we want to maintain. :)

Personally I would get rid of this block at all. You would normally pass such flags via CFLAGS, don't you? I also can't remember any project providing a dedicated flag for things like that.

However, you maybe want to keep that and I don't want to break your framework or ask you to remove features you like. But would you accept at least a PR which would make this block optional?

I am not sure about the option name, maybe `--{enable,disable}-debug-symbols`?

**Comment by edenhill** [comment]
Debug symbols have been root of all kinds of weird errors on OSX (clang crashes, for instance) and it took me a good while to find the proper options to use (`-gstrict-dwarf`..?), a mess.

I agree that it should be possible to toggle debug symbols, but I'd like to keep them enabled by default since they're most useful for new users who hastily download, build, code and crash.
Advanced users can disable it at configure time as you suggest.

`- -{enable,disable}-debug-symbols` sounds good.
